---
# jma-service

apiVersion: v1
kind: Service
metadata:
    name: jma

spec:
    selector:
        name: jma-pod
        app: java-maven-app
    type: NodePort
    ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000